name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build Solution
        run: dotnet build --configuration Release --property Platform="Any CPU"

      - name: Pack both frameworks
        run: dotnet pack --configuration Release --output ./artifacts

      - name: Get previous tag
        id: previous_tag
        run: |
          git fetch --tags --force
          previous_tag=$(git tag --sort=-creatordate | sed -n '2p')
          echo "previous_tag=$previous_tag" >> $GITHUB_ENV

      - name: Generate changelog
        id: changelog
        run: |
          if [ -z "$PREVIOUS_TAG" ]; then
            changelog=$(git log --pretty=format:"- %s")
          else
            changelog=$(git log "$PREVIOUS_TAG"..HEAD --pretty=format:"- %s")
          fi
          echo "changelog=$changelog" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          body: ${{ env.changelog }}
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload NuGet packages to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: './artifacts/*.nupkg'
          asset_name: SharpPluginSystem_${{ github.ref_name }}.nupkg
          asset_content_type: application/zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push all NuGet packages to NuGet registry
        run: dotnet nuget push ./artifacts/*.nupkg --api-key ${{ secrets.NUGET_TOKEN }} --source https://api.nuget.org/v3/index.json --skip-duplicate
